// ═══════════════════════════════════════════════════════════
// SimPhase — Firms & Challenges Catalog
// Single source of truth for all prop firm rules.
// Rules verified against official sources: June 2026.
// ═══════════════════════════════════════════════════════════

import type { Firm, Challenge } from './types';

/** Shown in the UI next to challenge cards. Update when rules are re-verified. */
export const RULES_VERIFIED = 'June 2026';

export const FIRMS: Record<string, Firm> = {
  ftmo: {
    id: 'ftmo', label: 'FTMO',
    description: 'Trusted CFD benchmark with clear classic rules.',
    highlight: 'CFD benchmark',
    challenges: ['ftmo_2step', 'ftmo_1step'],
  },
  topstep: {
    id: 'topstep', label: 'Topstep',
    description: 'Futures combine on a monthly subscription, with trailing drawdown and a consistency rule.',
    highlight: 'Futures combine',
    challenges: ['topstep_combine'],
  },
  fundednext: {
    id: 'fundednext', label: 'FundedNext',
    description: 'Large CFD player with the Stellar models and clean balance-based limits.',
    highlight: 'Strong perceived value',
    challenges: ['fn_2step', 'fn_1step', 'fn_lite'],
  },
  fundingpips: {
    id: 'fundingpips', label: 'FundingPips',
    description: 'Popular low-cost CFD firm. Core 2-Step modeled precisely.',
    highlight: 'Budget CFD path',
    challenges: ['fp_2step'],
  },
};

export const CHALLENGES: Record<string, Challenge> = {
  ftmo_2step: {
    id: 'ftmo_2step', firm: 'ftmo', name: '2-Step', longName: 'FTMO 2-Step',
    ruleLabel: '10% / 5% · 5% MDL · 10% static max loss',
    description: 'Classic FTMO evaluation with the clearest and most recognizable rule set. Fee refunded with first reward withdrawal.',
    confidence: 'verified', rulesVerified: 'June 2026',
    sizes: [10000, 25000, 50000, 100000, 200000],
    feeDefaults: { 10000: 155, 25000: 250, 50000: 345, 100000: 540, 200000: 1080 },
    feeModel: 'one_time', activationFee: 0,
    phases: [
      { target: 0.10, minDays: 4 },
      { target: 0.05, minDays: 4 },
    ],
    dailyLoss: 0.05, overallLoss: 0.10,
    trailing: 'none',
    bestDayCap: null, consistencyCap: null, market: 'cfd',
    confidenceNote: 'Official rules verified June 2026. Both phases are simulated with limits resetting between phases.',
    feeNote: 'Fee defaults are best-effort values and editable. FTMO says the 2-Step fee is refunded with the first reward withdrawal.',
    failureBase: 'Daily loss breach',
  },
  ftmo_1step: {
    id: 'ftmo_1step', firm: 'ftmo', name: '1-Step', longName: 'FTMO 1-Step',
    ruleLabel: '10% target · 3% MDL · 10% EOD trailing · 50% best day',
    description: 'Faster path, but materially more fragile: tighter daily loss, EOD trailing max loss, and a best-day rule that can delay your pass.',
    confidence: 'verified', rulesVerified: 'June 2026',
    sizes: [10000, 25000, 50000, 100000, 200000],
    feeDefaults: { 10000: 89, 25000: 199, 50000: 299, 100000: 499, 200000: 999 },
    feeModel: 'one_time', activationFee: 0,
    phases: [{ target: 0.10, minDays: 1 }],
    dailyLoss: 0.03, overallLoss: null,
    trailing: 'eod', trailingPct: 0.10, trailingFreezesAtInitial: true,
    bestDayCap: 0.50, consistencyCap: null, market: 'cfd',
    confidenceNote: 'Verified June 2026. Note: exceeding the 50% Best Day rule is not a breach — it forces you to keep trading until your best day is under 50% of positive days\u2019 profit. SimPhase simulates that delay and the extra drawdown exposure it creates.',
    feeNote: 'Fee defaults are editable. FTMO says the 1-Step fee is not refunded after passing.',
    failureBase: 'Trailing drawdown pressure',
  },
  topstep_combine: {
    id: 'topstep_combine', firm: 'topstep', name: 'Trading Combine', longName: 'Topstep Trading Combine',
    ruleLabel: '$3k/$6k/$9k target · intraday trailing MLL · 50% consistency',
    description: 'Monthly subscription combine. The intraday trailing Maximum Loss Limit and the consistency rule are the real difficulty — both are simulated.',
    confidence: 'verified', rulesVerified: 'June 2026',
    sizes: [50000, 100000, 150000],
    feeDefaults: { 50000: 49, 100000: 99, 150000: 149 },
    feeModel: 'monthly', activationFee: 149,
    phases: [{ target: null, targetDollar: { 50000: 3000, 100000: 6000, 150000: 9000 }, minDays: 2 }],
    dailyLoss: 0, overallLoss: null,
    overallLossDollar: { 50000: 2000, 100000: 3000, 150000: 4500 },
    trailing: 'intraday',
    trailingDollar: { 50000: 2000, 100000: 3000, 150000: 4500 },
    trailingFreezesAtInitial: true,
    bestDayCap: null, consistencyCap: 0.50, market: 'futures',
    confidenceNote: 'Verified June 2026. The Daily Loss Limit locks the day, not the account, so it is not modeled as a failure. The trailing MLL follows the intraday equity high and freezes at the starting balance. Cost is modeled as a monthly subscription: failed attempts inside a month are covered by reset credits.',
    feeNote: 'Subscription is billed monthly ($49/$99/$149) and each renewal includes a reset credit. A one-time $149 activation fee is added on successful funding (Standard path).',
    failureBase: 'Trailing drawdown',
  },
  fn_2step: {
    id: 'fn_2step', firm: 'fundednext', name: 'Stellar 2-Step', longName: 'FundedNext Stellar 2-Step',
    ruleLabel: '8% / 5% · 5% MDL · 10% max loss',
    description: 'Strong commercial alternative to FTMO with a lower first-phase target and a similar drawdown profile.',
    confidence: 'verified', rulesVerified: 'June 2026',
    sizes: [6000, 15000, 25000, 50000, 100000, 200000],
    feeDefaults: { 6000: 59.99, 15000: 119.99, 25000: 199.99, 50000: 299.99, 100000: 549.99, 200000: 1099.99 },
    feeModel: 'one_time', activationFee: 0,
    phases: [
      { target: 0.08, minDays: 5 },
      { target: 0.05, minDays: 5 },
    ],
    dailyLoss: 0.05, overallLoss: 0.10,
    trailing: 'none',
    bestDayCap: null, consistencyCap: null, market: 'cfd',
    confidenceNote: 'Official Stellar 2-Step rules verified June 2026. Balance-based static limits, simulated per phase.',
    feeNote: 'Official current plan fee is prefilled and editable.',
    failureBase: 'Daily loss breach',
  },
  fn_1step: {
    id: 'fn_1step', firm: 'fundednext', name: 'Stellar 1-Step', longName: 'FundedNext Stellar 1-Step',
    ruleLabel: '10% target · 3% MDL · 6% max loss',
    description: 'Faster evaluation path with a materially smaller loss envelope. One bad session can end the attempt.',
    confidence: 'verified', rulesVerified: 'June 2026',
    sizes: [6000, 15000, 25000, 50000, 100000, 200000],
    feeDefaults: { 6000: 59.99, 15000: 119.99, 25000: 199.99, 50000: 299.99, 100000: 549.99, 200000: 1099.99 },
    feeModel: 'one_time', activationFee: 0,
    phases: [{ target: 0.10, minDays: 2 }],
    dailyLoss: 0.03, overallLoss: 0.06,
    trailing: 'none',
    bestDayCap: null, consistencyCap: null, market: 'cfd',
    confidenceNote: 'Verified June 2026. The challenge is harsher because the loss envelope (6%) is materially smaller than the target (10%).',
    feeNote: 'FundedNext prices Stellar 1-Step in line with Stellar 2-Step. Defaults are editable.',
    failureBase: 'Daily loss breach',
  },
  fn_lite: {
    id: 'fn_lite', firm: 'fundednext', name: 'Stellar Lite', longName: 'FundedNext Stellar Lite',
    ruleLabel: '8% / 4% · 4% MDL · 8% max loss',
    description: 'Budget entry with a lower second-phase target but tighter balance-based loss limits.',
    confidence: 'verified', rulesVerified: 'June 2026',
    sizes: [5000, 10000, 25000, 50000, 100000, 200000],
    feeDefaults: { 5000: 32.99, 10000: 59.99, 25000: 139.99, 50000: 229.99, 100000: 399.99, 200000: 798.99 },
    feeModel: 'one_time', activationFee: 0,
    phases: [
      { target: 0.08, minDays: 5 },
      { target: 0.04, minDays: 5 },
    ],
    dailyLoss: 0.04, overallLoss: 0.08,
    trailing: 'none',
    bestDayCap: null, consistencyCap: null, market: 'cfd',
    confidenceNote: 'Rules verified June 2026 against current help documentation.',
    feeNote: 'Default fee is prefilled from currently available official pricing references and remains editable.',
    failureBase: 'Daily loss breach',
  },
  fp_2step: {
    id: 'fp_2step', firm: 'fundingpips', name: '2-Step', longName: 'FundingPips 2-Step',
    ruleLabel: '8% / 5% · 5% MDL · 10% max loss · 3 days/phase',
    description: 'The standard FundingPips evaluation — the variant most traders actually buy, modeled precisely.',
    confidence: 'verified', rulesVerified: 'June 2026',
    sizes: [5000, 10000, 25000, 50000, 100000],
    feeDefaults: { 5000: 29, 10000: 59, 25000: 139, 50000: 289, 100000: 499 },
    feeModel: 'one_time', activationFee: 0,
    phases: [
      { target: 0.08, minDays: 3 },
      { target: 0.05, minDays: 3 },
    ],
    dailyLoss: 0.05, overallLoss: 0.10,
    trailing: 'none',
    bestDayCap: null, consistencyCap: null, market: 'cfd',
    confidenceNote: 'Verified June 2026. Drawdown counters reset between phases; the balance carries over. Pricing moves often — double-check the fee.',
    feeNote: 'Fee is editable. Defaults are prefilled from current public references.',
    failureBase: 'Daily loss breach',
  },
};
